# Generated by Django 3.1.5 on 2021-07-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210724_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics'),
        ),
    ]
