# Generated by Django 3.1.5 on 2021-09-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(limit_choices_to={'country': models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.country')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.city'),
        ),
    ]
