# Generated by Django 3.1.5 on 2021-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frontpic',
            field=models.ImageField(default='front_pics/default_post.png', upload_to='front_pics'),
        ),
    ]
