# Generated by Django 3.1.5 on 2021-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210727_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
