# Generated by Django 3.1.5 on 2021-09-04 21:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210805_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frontpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
